#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/shiro_db
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
#    username: root
#    password: root
shiro:
  loginUrl: /unanth
  sessionManager:
    sessionIdUrlRewritingEnabled: false
cas:
  client-name: mfgClient
  server:
    url: https://tcas.zhuzher.com
    login-url: https://tcas.zhuzher.com/login
  project:
    url: http://127.0.0.1:8080